jdk:
  - oraclejdk7

language: java

sudo: false

services:
  - docker

before_install:
  - pip install --user codecov

install:
  - travis_wait mvn clean

script: ./travis.sh

after_success:
  - codecov